name: mobile_burguers
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/item1.png
    - assets/item2.png
    - assets/item3.png
    - assets/item4.png
    - assets/item5.png
    - assets/item6.png
    - assets/item7.png
    - assets/item8.png
    - assets/item9.png
    - assets/item10.png
    - assets/item11.png
    - assets/item12.png
    - assets/item13.png
